// Package binsolver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package binsolver

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for GroupMode.
const (
	KeepTogether GroupMode = "keepTogether"
	Separate     GroupMode = "separate"
)

// Defines values for NestedPlacementRotation.
const (
	NestedPlacementRotationXyz NestedPlacementRotation = "xyz"
	NestedPlacementRotationXzy NestedPlacementRotation = "xzy"
	NestedPlacementRotationYxz NestedPlacementRotation = "yxz"
	NestedPlacementRotationYzx NestedPlacementRotation = "yzx"
	NestedPlacementRotationZxy NestedPlacementRotation = "zxy"
	NestedPlacementRotationZyx NestedPlacementRotation = "zyx"
)

// Defines values for PackRequestLabelFormat.
const (
	PackRequestLabelFormatNone PackRequestLabelFormat = "none"
	PackRequestLabelFormatZpl  PackRequestLabelFormat = "zpl"
)

// Defines values for PackRequestNestingStrategy.
const (
	PackRequestNestingStrategyAuto     PackRequestNestingStrategy = "auto"
	PackRequestNestingStrategyMaximize PackRequestNestingStrategy = "maximize"
	PackRequestNestingStrategyNone     PackRequestNestingStrategy = "none"
)

// Defines values for PackRequestObjective.
const (
	Fast      PackRequestObjective = "fast"
	MaxPlaced PackRequestObjective = "maxPlaced"
	MinBins   PackRequestObjective = "minBins"
	MinCost   PackRequestObjective = "minCost"
	MinWaste  PackRequestObjective = "minWaste"
	Shipping  PackRequestObjective = "shipping"
)

// Defines values for PlacementRotation.
const (
	PlacementRotationXyz PlacementRotation = "xyz"
	PlacementRotationXzy PlacementRotation = "xzy"
	PlacementRotationYxz PlacementRotation = "yxz"
	PlacementRotationYzx PlacementRotation = "yzx"
	PlacementRotationZxy PlacementRotation = "zxy"
	PlacementRotationZyx PlacementRotation = "zyx"
)

// Defines values for RotationMode.
const (
	Any     RotationMode = "any"
	Axis    RotationMode = "axis"
	Custom  RotationMode = "custom"
	NoFlip  RotationMode = "noFlip"
	None    RotationMode = "none"
	Upright RotationMode = "upright"
)

// Defines values for RotationRulesInputAllowed.
const (
	Xyz RotationRulesInputAllowed = "xyz"
	Xzy RotationRulesInputAllowed = "xzy"
	Yxz RotationRulesInputAllowed = "yxz"
	Yzx RotationRulesInputAllowed = "yzx"
	Zxy RotationRulesInputAllowed = "zxy"
	Zyx RotationRulesInputAllowed = "zyx"
)

// BinInput defines model for BinInput.
type BinInput struct {
	// AllowHazmat If false, hazmat items cannot be placed in this bin. Defaults to true.
	AllowHazmat *bool `json:"allowHazmat,omitempty"`

	// Cost Cost of using this bin (required for minCost objective).
	Cost *float64 `json:"cost,omitempty"`

	// D Bin depth (Z axis).
	D float64 `json:"d"`

	// H Bin height (Y axis).
	H float64 `json:"h"`

	// Id Optional bin identifier. If omitted, the API assigns one.
	Id *string `json:"id,omitempty"`

	// MaxWeight Maximum weight capacity of this bin (sum of item weights).
	MaxWeight *float64 `json:"maxWeight,omitempty"`

	// Padding Padding/clearance values (all sets defaults for x/y/z).
	Padding *PaddingInput `json:"padding,omitempty"`

	// Quantity When set, must not exceed plan limits (free 100, paid 1000).
	Quantity *int `json:"quantity,omitempty"`

	// Shipping Shipping profile for a bin or container.
	Shipping *ShippingInput `json:"shipping,omitempty"`

	// TareWeight Empty weight of the bin or pallet (added to shipment weight).
	TareWeight *float64 `json:"tareWeight,omitempty"`

	// W Bin width (X axis).
	W float64 `json:"w"`
}

// BinResult defines model for BinResult.
type BinResult struct {
	// BinId Instance id for the packed bin.
	BinId string `json:"binId"`

	// D Bin depth.
	D float64 `json:"d"`

	// H Bin height.
	H float64 `json:"h"`

	// Instructions Step-by-step packing instructions (if requested).
	Instructions *[]string `json:"instructions,omitempty"`

	// Label Generated label code (e.g. ZPL) for the bin (if requested).
	Label *string `json:"label,omitempty"`

	// Placements Item placements in this bin.
	Placements []Placement     `json:"placements"`
	Shipping   *ShippingResult `json:"shipping,omitempty"`

	// TemplateId Template id from the request.
	TemplateId string `json:"templateId"`

	// Utilization Volume utilization of the bin (0.0 to 1.0).
	Utilization float64 `json:"utilization"`

	// VizUrl URL to replay this bin packing result in the BinSolver visualizer.
	VizUrl string `json:"vizUrl"`

	// W Bin width.
	W float64 `json:"w"`

	// Weight Total weight of items in this bin.
	Weight *float64 `json:"weight,omitempty"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	// Code Machine-readable error code.
	Code string `json:"code"`

	// Message Human-readable error message.
	Message string `json:"message"`

	// RequestId Request identifier when provided.
	RequestId *string `json:"requestId,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorBody `json:"error"`
}

// GroupMode Grouping mode for items sharing the same group id. groupMode without group is invalid.
type GroupMode string

// ItemInput defines model for ItemInput.
type ItemInput struct {
	// AllowRotation If true, the item can be rotated 90 degrees on any axis. Defaults to true.
	AllowRotation *bool `json:"allowRotation,omitempty"`

	// D Item depth (Z axis).
	D float64 `json:"d"`

	// H Item height (Y axis).
	H float64 `json:"h"`

	// Id Optional item identifier. If omitted, the API assigns one.
	Id *string `json:"id,omitempty"`

	// Packaging Packaging and compatibility constraints.
	Packaging *PackagingRulesInput `json:"packaging,omitempty"`

	// Quantity When set, total expanded items must remain within plan limits (free 100, paid 1000).
	Quantity *int `json:"quantity,omitempty"`

	// Rotation Controls which rotations are allowed for this item.
	Rotation *RotationRulesInput `json:"rotation,omitempty"`

	// Stacking Stability and stacking constraints for this item.
	Stacking *StackingRulesInput `json:"stacking,omitempty"`

	// W Item width (X axis).
	W float64 `json:"w"`

	// Weight Weight of a single unit of this item (used for load limits and shipping).
	Weight *float64 `json:"weight,omitempty"`
}

// NestedPlacement defines model for NestedPlacement.
type NestedPlacement struct {
	// D Packed depth (includes item padding if provided).
	D float64 `json:"d"`

	// H Packed height (includes item padding if provided).
	H float64 `json:"h"`

	// ItemId Item identifier for this placement.
	ItemId string `json:"itemId"`

	// Rotation Applied rotation permutation.
	Rotation NestedPlacementRotation `json:"rotation"`

	// W Packed width (includes item padding if provided).
	W float64 `json:"w"`

	// X X coordinate of the placement origin (relative to container).
	X float64 `json:"x"`

	// Y Y coordinate of the placement origin (relative to container).
	Y float64 `json:"y"`

	// Z Z coordinate of the placement origin (relative to container).
	Z float64 `json:"z"`
}

// NestedPlacementRotation Applied rotation permutation.
type NestedPlacementRotation string

// NestingRulesInput Internal cavity definition for nesting.
type NestingRulesInput struct {
	// AllowHazmat If false, hazmat items cannot be nested inside this cavity. Defaults to true.
	AllowHazmat *bool `json:"allowHazmat,omitempty"`

	// AllowedGroups If set, only items whose packaging.group is in this list may be nested.
	AllowedGroups *[]string `json:"allowedGroups,omitempty"`

	// InnerD Inner cavity depth (Z axis).
	InnerD float64 `json:"innerD"`

	// InnerH Inner cavity height (Y axis).
	InnerH float64 `json:"innerH"`

	// InnerW Inner cavity width (X axis).
	InnerW float64 `json:"innerW"`

	// MaxWeight Maximum total weight allowed inside this cavity.
	MaxWeight *float64 `json:"maxWeight,omitempty"`

	// Padding Padding/clearance values (all sets defaults for x/y/z).
	Padding *PaddingInput `json:"padding,omitempty"`
}

// PackRequest defines model for PackRequest.
type PackRequest struct {
	// AllowUnplaced When false, the request fails if any item cannot be placed. Defaults to true.
	AllowUnplaced *bool `json:"allowUnplaced,omitempty"`

	// Bins Bin templates to pack into. Maximum bin types per request is plan-dependent (free 50, paid 200).
	Bins []BinInput `json:"bins"`

	// IncludeInstructions If true, returns step-by-step packing instructions for each bin. (Paid plan only) Defaults to false.
	IncludeInstructions *bool `json:"includeInstructions,omitempty"`

	// Items Items to pack (expanded by quantity). Maximum items per request is plan-dependent (free 100, paid 1000).
	Items []ItemInput `json:"items"`

	// LabelFormat If 'zpl', generates a ZPL label string for each bin. (Paid plan only) Defaults to 'none'.
	LabelFormat *PackRequestLabelFormat `json:"labelFormat,omitempty"`

	// NestingStrategy Controls pre-pack nesting. auto uses the main objective to decide nesting; maximize fills cavities first; none disables nesting. Defaults to 'auto'.
	NestingStrategy *PackRequestNestingStrategy `json:"nestingStrategy,omitempty"`

	// Objective Packing objective (speed, bins used, placed count, waste minimization, cost, or shipping). minCost requires bin cost values; shipping requires bin shipping profiles. Defaults to 'fast'.
	Objective *PackRequestObjective `json:"objective,omitempty"`

	// Palletization Two-stage packing: items -> pallets -> containers.
	Palletization *PalletizationInput `json:"palletization,omitempty"`

	// ShippingObjective Weights used to score shipping tradeoffs during optimization.
	ShippingObjective *ShippingObjectiveInput `json:"shippingObjective,omitempty"`
}

// PackRequestLabelFormat If 'zpl', generates a ZPL label string for each bin. (Paid plan only) Defaults to 'none'.
type PackRequestLabelFormat string

// PackRequestNestingStrategy Controls pre-pack nesting. auto uses the main objective to decide nesting; maximize fills cavities first; none disables nesting. Defaults to 'auto'.
type PackRequestNestingStrategy string

// PackRequestObjective Packing objective (speed, bins used, placed count, waste minimization, cost, or shipping). minCost requires bin cost values; shipping requires bin shipping profiles. Defaults to 'fast'.
type PackRequestObjective string

// PackResponse defines model for PackResponse.
type PackResponse struct {
	// Bins Packed bins (containers) with placements.
	Bins []BinResult `json:"bins"`

	// Pallets Packed pallets when palletization is enabled.
	Pallets *[]BinResult `json:"pallets,omitempty"`

	// Splits Item-to-container assignments with pallet audit trails.
	Splits *[]SplitAssignment `json:"splits,omitempty"`
	Stats  PackStats          `json:"stats"`

	// Unplaced Items that could not be placed.
	Unplaced []UnplacedItem `json:"unplaced"`

	// UnplacedPallets Pallets that could not be placed into containers.
	UnplacedPallets *[]UnplacedPallet `json:"unplacedPallets,omitempty"`
}

// PackStats defines model for PackStats.
type PackStats struct {
	// BinsUsed Number of bins used.
	BinsUsed int `json:"binsUsed"`

	// DurationMs Packing duration in milliseconds.
	DurationMs int64 `json:"durationMs"`

	// Items Total items requested (after quantity expansion).
	Items int `json:"items"`

	// Nested Number of items nested inside other items.
	Nested *int `json:"nested,omitempty"`

	// PalletsUsed Number of pallets used (if palletization enabled).
	PalletsUsed *int `json:"palletsUsed,omitempty"`

	// Placed Number of items successfully placed.
	Placed int `json:"placed"`

	// RequestId Echoed request id when provided.
	RequestId *string `json:"requestId,omitempty"`

	// Unplaced Number of items not placed.
	Unplaced int `json:"unplaced"`
}

// PackagingRulesInput Packaging and compatibility constraints.
type PackagingRulesInput struct {
	// Fragile Marks item as fragile; prevents stacking weight above.
	Fragile *bool `json:"fragile,omitempty"`

	// Group Group identifier. Items sharing the same group id are governed by groupMode.
	Group *string `json:"group,omitempty"`

	// GroupMode Grouping mode for items sharing the same group id. groupMode without group is invalid.
	GroupMode *GroupMode `json:"groupMode,omitempty"`

	// Hazmat Marks item as hazardous; requires allowHazmat=true on bins.
	Hazmat *bool `json:"hazmat,omitempty"`

	// Nestable When false, this item cannot be nested inside other items. Defaults to true.
	Nestable *bool `json:"nestable,omitempty"`

	// Nesting Internal cavity definition for nesting.
	Nesting *NestingRulesInput `json:"nesting,omitempty"`

	// Padding Padding/clearance values (all sets defaults for x/y/z).
	Padding *PaddingInput `json:"padding,omitempty"`
}

// PaddingInput Padding/clearance values (all sets defaults for x/y/z).
type PaddingInput struct {
	// All Uniform padding on all axes.
	All *float64 `json:"all,omitempty"`

	// X Padding on the X axis.
	X *float64 `json:"x,omitempty"`

	// Y Padding on the Y axis.
	Y *float64 `json:"y,omitempty"`

	// Z Padding on the Z axis.
	Z *float64 `json:"z,omitempty"`
}

// PalletizationInput Two-stage packing: items -> pallets -> containers.
type PalletizationInput struct {
	// AllowMixedContainers When false, all pallets must fit a single container template.
	AllowMixedContainers *bool `json:"allowMixedContainers,omitempty"`

	// Pallets Pallet templates used for the first packing stage.
	Pallets []BinInput `json:"pallets"`
}

// Placement defines model for Placement.
type Placement struct {
	// D Packed depth (includes item padding if provided).
	D float64 `json:"d"`

	// H Packed height (includes item padding if provided).
	H float64 `json:"h"`

	// ItemId Item identifier for this placement.
	ItemId string `json:"itemId"`

	// Nested Items packed inside this item (if nesting was used). Coordinates are relative to the item's local origin.
	Nested *[]NestedPlacement `json:"nested,omitempty"`

	// Rotation Applied rotation permutation.
	Rotation PlacementRotation `json:"rotation"`

	// W Packed width (includes item padding if provided).
	W float64 `json:"w"`

	// X X coordinate of the placement origin.
	X float64 `json:"x"`

	// Y Y coordinate of the placement origin.
	Y float64 `json:"y"`

	// Z Z coordinate of the placement origin.
	Z float64 `json:"z"`
}

// PlacementRotation Applied rotation permutation.
type PlacementRotation string

// RotationAxes Allowed axis swaps for axis-specific rotation control.
type RotationAxes struct {
	// Xy Allow swapping X and Y.
	Xy *bool `json:"xy,omitempty"`

	// Xz Allow swapping X and Z.
	Xz *bool `json:"xz,omitempty"`

	// Yz Allow swapping Y and Z.
	Yz *bool `json:"yz,omitempty"`
}

// RotationMode Rotation mode selector.
type RotationMode string

// RotationRulesInput Controls which rotations are allowed for this item.
type RotationRulesInput struct {
	// AllowAxes Allowed axis swaps for axis-specific rotation control.
	AllowAxes *RotationAxes `json:"allowAxes,omitempty"`

	// Allowed Allowed explicit rotations when mode=custom.
	Allowed *[]RotationRulesInputAllowed `json:"allowed,omitempty"`

	// Mode Rotation mode selector.
	Mode *RotationMode `json:"mode,omitempty"`
}

// RotationRulesInputAllowed defines model for RotationRulesInput.Allowed.
type RotationRulesInputAllowed string

// ShippingInput Shipping profile for a bin or container.
type ShippingInput struct {
	// BaseCost Fixed cost per shipment for this bin.
	BaseCost *float64 `json:"baseCost,omitempty"`

	// CarbonPerWeight Carbon cost per unit of billable weight.
	CarbonPerWeight *float64 `json:"carbonPerWeight,omitempty"`

	// DimWeightDivisor Divisor for dimensional weight (volume / divisor).
	DimWeightDivisor *float64 `json:"dimWeightDivisor,omitempty"`

	// RatePerWeight Variable cost per unit of billable weight.
	RatePerWeight *float64 `json:"ratePerWeight,omitempty"`

	// SlaDays Estimated delivery time for this bin.
	SlaDays *float64 `json:"slaDays,omitempty"`
}

// ShippingObjectiveInput Weights used to score shipping tradeoffs during optimization.
type ShippingObjectiveInput struct {
	// CarbonWeight Weight applied to carbon impact in the shipping objective.
	CarbonWeight *float64 `json:"carbonWeight,omitempty"`

	// CostWeight Weight applied to cost in the shipping objective.
	CostWeight *float64 `json:"costWeight,omitempty"`

	// DimWeightDivisor Override bin shipping dimWeightDivisor for optimization.
	DimWeightDivisor *float64 `json:"dimWeightDivisor,omitempty"`

	// SlaWeight Weight applied to SLA days in the shipping objective (lower is better).
	SlaWeight *float64 `json:"slaWeight,omitempty"`
}

// ShippingResult defines model for ShippingResult.
type ShippingResult struct {
	// BillableWeight max(actual weight, dimensional weight).
	BillableWeight float64 `json:"billableWeight"`

	// Carbon Estimated carbon impact.
	Carbon float64 `json:"carbon"`

	// Cost Estimated shipping cost.
	Cost float64 `json:"cost"`

	// DimensionalWeight Dimensional weight computed from bin volume and divisor.
	DimensionalWeight float64 `json:"dimensionalWeight"`

	// SlaDays Estimated delivery time in days.
	SlaDays float64 `json:"slaDays"`
}

// SplitAssignment defines model for SplitAssignment.
type SplitAssignment struct {
	// BinId Container/bin identifier where the item ultimately lands.
	BinId string `json:"binId"`

	// ItemId Item identifier.
	ItemId string `json:"itemId"`

	// PalletId Pallet identifier if palletization was used.
	PalletId *string `json:"palletId,omitempty"`
}

// StackingRulesInput Stability and stacking constraints for this item.
type StackingRulesInput struct {
	// MaxLoad Maximum load this item can support above it.
	MaxLoad *float64 `json:"maxLoad,omitempty"`

	// MaxStackHeight Maximum stacked height above this item.
	MaxStackHeight *float64 `json:"maxStackHeight,omitempty"`

	// MinSupportArea Minimum supported base area (absolute units).
	MinSupportArea *float64 `json:"minSupportArea,omitempty"`

	// MinSupportRatio Minimum supported base area ratio (0..1).
	MinSupportRatio *float64 `json:"minSupportRatio,omitempty"`

	// RequireCogSupport Require center-of-gravity to be supported.
	RequireCogSupport *bool `json:"requireCogSupport,omitempty"`
}

// UnplacedItem defines model for UnplacedItem.
type UnplacedItem struct {
	// D Item depth.
	D float64 `json:"d"`

	// H Item height.
	H float64 `json:"h"`

	// ItemId Item identifier.
	ItemId string `json:"itemId"`

	// Reason Reason code for why the item was not placed (e.g., no_fit, pallet_unplaced).
	Reason string `json:"reason"`

	// W Item width.
	W float64 `json:"w"`

	// Weight Item weight.
	Weight *float64 `json:"weight,omitempty"`
}

// UnplacedPallet defines model for UnplacedPallet.
type UnplacedPallet struct {
	// PalletId Pallet instance id.
	PalletId string `json:"palletId"`

	// Reason Reason code for why the pallet was not placed.
	Reason string `json:"reason"`
}

// PostPackParams defines parameters for PostPack.
type PostPackParams struct {
	// XRequestId Optional request correlation id.
	XRequestId *string `json:"x-request-id,omitempty"`
}

// PostV1PackParams defines parameters for PostV1Pack.
type PostV1PackParams struct {
	// XRequestId Optional request correlation id.
	XRequestId *string `json:"x-request-id,omitempty"`
}

// PostPackJSONRequestBody defines body for PostPack for application/json ContentType.
type PostPackJSONRequestBody = PackRequest

// PostV1PackJSONRequestBody defines body for PostV1Pack for application/json ContentType.
type PostV1PackJSONRequestBody = PackRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// Get request
	Get(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostPackWithBody request with any body
	PostPackWithBody(ctx context.Context, params *PostPackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostPack(ctx context.Context, params *PostPackParams, body PostPackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1PackWithBody request with any body
	PostV1PackWithBody(ctx context.Context, params *PostV1PackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1Pack(ctx context.Context, params *PostV1PackParams, body PostV1PackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) Get(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPackWithBody(ctx context.Context, params *PostPackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPackRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPack(ctx context.Context, params *PostPackParams, body PostPackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPackRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1PackWithBody(ctx context.Context, params *PostV1PackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1PackRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1Pack(ctx context.Context, params *PostV1PackParams, body PostV1PackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1PackRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetRequest generates requests for Get
func NewGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostPackRequest calls the generic PostPack builder with application/json body
func NewPostPackRequest(server string, params *PostPackParams, body PostPackJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostPackRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostPackRequestWithBody generates requests for PostPack with any type of body
func NewPostPackRequestWithBody(server string, params *PostPackParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pack")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XRequestId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "x-request-id", runtime.ParamLocationHeader, *params.XRequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-request-id", headerParam0)
		}

	}

	return req, nil
}

// NewPostV1PackRequest calls the generic PostV1Pack builder with application/json body
func NewPostV1PackRequest(server string, params *PostV1PackParams, body PostV1PackJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1PackRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostV1PackRequestWithBody generates requests for PostV1Pack with any type of body
func NewPostV1PackRequestWithBody(server string, params *PostV1PackParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/pack")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XRequestId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "x-request-id", runtime.ParamLocationHeader, *params.XRequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-request-id", headerParam0)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetWithResponse request
	GetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// PostPackWithBodyWithResponse request with any body
	PostPackWithBodyWithResponse(ctx context.Context, params *PostPackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPackResponse, error)

	PostPackWithResponse(ctx context.Context, params *PostPackParams, body PostPackJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPackResponse, error)

	// PostV1PackWithBodyWithResponse request with any body
	PostV1PackWithBodyWithResponse(ctx context.Context, params *PostV1PackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1PackResponse, error)

	PostV1PackWithResponse(ctx context.Context, params *PostV1PackParams, body PostV1PackJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1PackResponse, error)
}

type GetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostPackResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PackResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON402      *ErrorResponse
	JSON403      *ErrorResponse
	JSON429      *ErrorResponse
	JSON502      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostPackResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostPackResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1PackResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PackResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON402      *ErrorResponse
	JSON403      *ErrorResponse
	JSON429      *ErrorResponse
	JSON502      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostV1PackResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1PackResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetWithResponse request returning *GetResponse
func (c *ClientWithResponses) GetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetResponse, error) {
	rsp, err := c.Get(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// PostPackWithBodyWithResponse request with arbitrary body returning *PostPackResponse
func (c *ClientWithResponses) PostPackWithBodyWithResponse(ctx context.Context, params *PostPackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPackResponse, error) {
	rsp, err := c.PostPackWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPackResponse(rsp)
}

func (c *ClientWithResponses) PostPackWithResponse(ctx context.Context, params *PostPackParams, body PostPackJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPackResponse, error) {
	rsp, err := c.PostPack(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPackResponse(rsp)
}

// PostV1PackWithBodyWithResponse request with arbitrary body returning *PostV1PackResponse
func (c *ClientWithResponses) PostV1PackWithBodyWithResponse(ctx context.Context, params *PostV1PackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1PackResponse, error) {
	rsp, err := c.PostV1PackWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1PackResponse(rsp)
}

func (c *ClientWithResponses) PostV1PackWithResponse(ctx context.Context, params *PostV1PackParams, body PostV1PackJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1PackResponse, error) {
	rsp, err := c.PostV1Pack(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1PackResponse(rsp)
}

// ParseGetResponse parses an HTTP response from a GetWithResponse call
func ParseGetResponse(rsp *http.Response) (*GetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostPackResponse parses an HTTP response from a PostPackWithResponse call
func ParsePostPackResponse(rsp *http.Response) (*PostPackResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostPackResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PackResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 402:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON402 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParsePostV1PackResponse parses an HTTP response from a PostV1PackWithResponse call
func ParsePostV1PackResponse(rsp *http.Response) (*PostV1PackResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1PackResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PackResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 402:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON402 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}
